### ISSUE TITLE
Could This library be used to declare dependency graph based workflows

### ISSUE THREAD

**Issue by diclophis** [wpengine/lostromos#56]
# My Issue

Could This library be used to declare dependency graph based workflows, such as defined by the `circleci/config.yml` specification: https://circleci.com/docs/2.0/configuration-reference/#requires

## Expected Behavior

Example reference of how a pod/deployment manifest might be annotated such that a given set of jobs may be started upon the completion of said jobs dependent jobs

## Current Behavior

I am unable to determine if said workflow is possible

## Possible Solution

Any advice / Solutions to implement said workflow of dependent job resolution would be appreciated

## Context

Cool idea?

## Your Environment

migrating a project from circleci to a pure kubernetes workflow

**Comment by nicolerenee** [comment]
I'm not sure I entirely understand what you are trying to accomplish here. My initial thought is that you might be able to use lostromos to accomplish this, but I need some more details. Could you explain in a little more details exactly how you envision what you are doing would work?

**Comment by nicolerenee** [comment]
You might be able to hack something together to get this to work, but it is not something that lostromos would be able to do for you.

**Comment by diclophis** [comment]
Ok, No worries, Thanks
