### ISSUE TITLE
[feature] Private Chart Repo support

### ISSUE THREAD

**Issue by so0k** [wpengine/lostromos#60]
## Question

We are looking at using Lostrómos, but we use a private Chart repository. Is there a plan on supporting this and if so, please advise on how we should think of the workflow?

Also, How does Lostrómos detect chart version changes?

**Comment by so0k** [comment]
Can chart version be part of the CRD and Lostrómos fetch that chart version from the private repo?

changing the chart version becomes then a matter of changing the release values in the CRD.

**Comment by nicolerenee** [comment]
I've been asked by multiple people to support adding the chart to the custom resource. I've considered how we would do this and I'm thinking maybe something like

```apiVersion: stable.nicolerenee.io/v1
kind: Character
metadata:
  name: thing1
spec:
  name: Thing 1
  from: Cat in the Hat
  by: Dr. Seuss
  lostromos:
    chart: character
```

initially this would still require the chart be on disk and be available to lostrómos when it is running just like today. But we could also add support for using repo. I haven't thought as much about what this would look like though. Just wondering if there is something stopping you from deploying lostrómos with the chart available to it? Or if you are just thinking this will make it easier?

**Comment by so0k** [comment]
Here's how we have Helm set up http://tech.honestbee.com/articles/devops/2017-07/drone-helm-repository (we are using chartmuseum now, but rest is pretty much the same) - it's very similar to how Reddit decided to set up their clusters.

We have a tiller per namespace but multiple different charts per namespace, we'd need a lostromos per chart per namespace?

With repo support, chart version should also be part of CR

**Comment by nicolerenee** [comment]
With the current implementation you would indeed need multiple lostromos deployments to support that. 
I think for this to work for you we would need to add the ability to support defining a chart on the CR directly. This would as you pointed out need to also include support for the chart version. 

I've been asked for this feature by multiple people now and it does seem like something we should add. We just need to also ensure we keep supporting the existing way of doing things for the time being. Let me spend some time figuring out exactly what this would look like from a technical solution and figure out how things play out a little in regards to Helm 3 supporting CRDs and go from there. Sound good?
