### ISSUE TITLE
[idea] integration with service-catalog?

### ISSUE THREAD

**Issue by arschles** [wpengine/lostromos#61]
# My Issue

This is a proposal to explore how lostromos might integrate with [service-catalog](https://github.com/kubernetes-incubator/service-catalog).

One idea to get started: if an operator uses lostromos exclusively to manage helm charts or manifest templates, perhaps lostromos could submit service-catalog [resources](https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/apis/servicecatalog/v1beta1/types.go) on the operator's behalf.

I don't have enough knowledge about how lostromos works to propose anything more detailed, but I'd love to chat about ideas if anyone is interested in exploring.

## Expected Behavior

N/A

## Current Behavior

N/A

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

N/A

1.
2.
3.
4.

## Context

N/A

## Your Environment

N/A

* Version used:
* Environment name and version (e.g. Golang 1.9 on K8s 1.7):
* Server type and version:
* Link to your project:

**Comment by nicolerenee** [comment]
I don't know much about how service catalog works. Let me dig into it and figure out if this needs something new to be added to lostromos or if this could already be supported using the existing templating we have in place.

**Comment by arschles** [comment]
Sounds good! Happy to answer any questions.
