### ISSUE TITLE
[enhancement] Add prometheus gauge for queue depth

### ISSUE THREAD

**Issue by mrsiesta** [wpengine/lostromos#73]
# My Issue

We need to know if lostromos is having any issue or slowness while processing new events. To that end we need a gauge in prometheus that indicates how many events are currently being processed.

## Expected Behavior

In process events should be visible via prometheus.

## Current Behavior

Currently we do not track the number of events in process.

## Possible Solution

Add a new metric endpoint for EventQueue and update the methods that generate events to increment the gauge on start and decrement the gauge on completion.

**Comment by nicolerenee** [comment]
Closing as this was incorrect. If it needs to be reopened let me know.
