### ISSUE TITLE
Sprig functions for Go templates

### ISSUE THREAD

**Issue by tylergarcianet** [wpengine/lostromos#75]
# My Issue

I would like to be able to use Sprig functions (https://github.com/Masterminds/sprig) when building my Go templates. Right now the libraries are not imported and functions are not defined.

## Expected Behavior

`{{ indent 8 .GetField "spec" "my_variable" }}`

I would expect this to call the indent function and indent all lines of text

## Current Behavior

`function \"indent\" not defined"`

## Possible Solution

I am unfamiliar with the Go language and unsure of how this would be implemented.

## Steps to Reproduce (for bugs)

NA

1.
2.
3.
4.

## Context

Sprig offers many functions that would help us to build our templates.

## Your Environment

NA

* Version used:
* Environment name and version (e.g. Golang 1.9 on K8s 1.7):
* Server type and version:
* Link to your project:

**Comment by nicolerenee** [comment]
I take it this is when you are using go templates?generally if you need more temp laying I would recommend you use helm as it supports doing full templating in a way that likely will never be implemented here for go templates.

**Comment by AssafKatz3** [comment]
@tylergarcianet The difference between just Sprig functions and HELM functions is significant, in context of Lostromos the most useful functions in HELM aren’t the ones that come from Sprig, but the internal ones – include, tpl, toYaml, etc. So I agree with @nicolerenee if you need it, use HELM functionlity.

**Comment by tylergarcianet** [comment]
Understood. Our deployments are at such a state of maturity it would require significant effort to refactor to use Helm templates. I wasn't sure if adding the Sprig functions to Go templating would be a trivial task or not. In any case, thank you very much for the explanations and hospitality.
